# Generated by Django 4.2.1 on 2023-07-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
