# Generated by Django 4.2.1 on 2023-07-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='brand',
        ),
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='station',
            name='opening_hours',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='place_id',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='imagePath',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
