# Generated by Django 4.2.1 on 2023-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_station_brand_station_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
