# Generated by Django 4.2.1 on 2023-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_station_gastypeinfo_alter_station_gastypes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='posted_by',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='valid_until',
            field=models.DateTimeField(null=True),
        ),
    ]
